### ISSUE TITLE
Script used to calculate numbers reported in Section 2.3.2. Toy example and tutorial?

### ISSUE THREAD

**Issue by mbnebel** [mbnebel/DeconfoundedFMRI#17]
@benjaminrisk @thebrisklab : Is this how you calculated the effect of ADOS on usability in the real data reported in Section 2.3.2?

https://github.com/mbnebel/DeconfoundedFMRI/blob/8f86e0922a6ec11893f64f828215d0db46ee9de3/ReviewerResponse/QC_Impacts_Analysis_RtoR_comparetosimulateddata.R#L188-L195

**Comment by BenjaminRisk** [comment]
Yes. I re-ran the code and am now getting -0.10 for the slope instead of -0.077 as reported in the paper. I think you have identified an issue here. I remember having -0.10 in an earlier version of the manuscript so not sure what is happening.

**Comment by BenjaminRisk** [comment]
Also, the paper has a typo where you fixed my first typo with 14.3-->14.5 but missed my second typo of 14.5 in the equation, see comment in overleaf

**Comment by mbnebel** [comment]
resolved with issue #18
