### ISSUE TITLE
change gam--> mgcv::gam

### ISSUE THREAD

**Issue by BenjaminRisk** [mbnebel/DeconfoundedFMRI#18]
https://github.com/mbnebel/DeconfoundedFMRI/blob/8f86e0922a6ec11893f64f828215d0db46ee9de3/ReviewerResponse/QC_Impacts_Analysis_RtoR_comparetosimulateddata.R#L183

**Comment by mbnebel** [comment]
resolved: 85d7cca32109ba25ba3ddd12556e1377d269048b
