### ISSUE TITLE
update readme 

### ISSUE THREAD

**Issue by mbnebel** [mbnebel/DeconfoundedFMRI#7]
1. ~~to reflect changes to the analysis~~
2. ~~add the bioRxiv citation~~ 5113cee0ec8257913a5e28501ae254e60cc750cf

**Comment by lidstone** [comment]
I added the nScans.Rdata file to the Data/noImputation/... directory without any errors. I only had one change to the directory on line 171 [changed load('./Data/nScans.RData') to load('./Data/noImputation/nScans.RData')]

[Exploring covariates, rs-fMRI usability, and functional connectivity.pdf](https://github.com/mbnebel/DeconfoundedFMRI/files/8354262/Exploring.covariates.rs-fMRI.usability.and.functional.connectivity.pdf)
